'use strict';
const HOSTS=new Set(['mediafire.com','www.mediafire.com','mega.nz','www.mega.nz']);
const files=[
{id:1,title:'Film Action 2024 - HD',desc:'Vidéo longue en qualité HD.',cat:'Vidéos',type:'🎬',size:'2.8 Go',provider:'MediaFire',duration:'02:15:30',img:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80',url:'https://www.mediafire.com/'},
{id:2,title:'Paysages Naturels - 4K',desc:'Collection d’images haute résolution.',cat:'Images',type:'🖼️',size:'12.4 Mo',provider:'MEGA',img:'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80',url:'https://mega.nz/'},
{id:3,title:'Game Booster Pro v1.2.3',desc:'Exemple d’application Android.',cat:'APK',type:'📱',size:'45 Mo',provider:'MEGA',url:'https://mega.nz/'},
{id:4,title:'Guide Utilisateur.pdf',desc:'Document PDF à télécharger.',cat:'PDF',type:'📄',size:'2.3 Mo',provider:'MediaFire',url:'https://www.mediafire.com/'},
{id:5,title:'Collection Films (ZIP)',desc:'Archive de fichiers compressés.',cat:'Archives',type:'📦',size:'4.8 Go',provider:'MEGA',url:'https://mega.nz/'},
{id:6,title:'Documentaire Nature',desc:'Documentaire en haute définition.',cat:'Vidéos',type:'🎬',size:'1.9 Go',provider:'MediaFire',duration:'01:45:20',img:'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=80',url:'https://www.mediafire.com/'}
];
const $=id=>document.getElementById(id), state={q:'',cat:'Toutes'};
function safe(u){try{const x=new URL(u);return x.protocol==='https:'&&HOSTS.has(x.hostname.toLowerCase())?x.href:null}catch{return null}}
function cats(){const c={};files.forEach(f=>c[f.cat]=(c[f.cat]||0)+1);return [{n:'Toutes',c:files.length},...Object.entries(c).map(([n,c])=>({n,c}))]}
function renderCats(){$('cats').replaceChildren(...cats().map(x=>{const b=document.createElement('button');b.className='cat '+(state.cat===x.n?'active':'');b.type='button';b.innerHTML='';const i=document.createElement('i');i.textContent=x.n==='Toutes'?'▦':({'Vidéos':'🎬','Images':'🖼️','APK':'📱','PDF':'📄','Archives':'📦'}[x.n]||'📁');const s=document.createElement('strong');s.textContent=x.n;const sm=document.createElement('small');sm.textContent=`${x.c} fichier${x.c>1?'s':''}`;b.append(i,s,sm);b.onclick=()=>{state.cat=x.n;renderCats();renderFiles()};return b}))}
function card(f){const a=safe(f.url),c=document.createElement('article');c.className='card';const t=document.createElement('div');t.className='thumb';if(f.img){const im=new Image();im.loading='lazy';im.referrerPolicy='no-referrer';im.alt='';im.src=f.img;im.onerror=()=>{im.remove();t.append(icon(f.type))};t.append(im)}else t.append(icon(f.type));const bd=document.createElement('div');bd.className='badge';bd.textContent=f.duration||f.cat;t.append(bd);const b=document.createElement('div');b.className='body';const h=document.createElement('h3');h.textContent=f.title;const p=document.createElement('p');p.className='desc';p.textContent=f.desc;const m=document.createElement('div');m.className='meta';m.textContent=`${f.size} • ${f.provider}`;const ac=document.createElement('div');ac.className='actions';const d=link(a?'⬇ Télécharger':'Lien indisponible',a,'dl');const pr=link(f.provider,a,'prov');ac.append(d,pr);b.append(h,p,m,ac);c.append(t,b);return c}
function icon(x){const e=document.createElement('span');e.className='ico';e.textContent=x;return e}
function link(text,url,cl){const a=document.createElement('a');a.className=cl;a.textContent=text;a.href=url||'#';if(url){a.target='_blank';a.rel='noopener noreferrer'}else a.onclick=e=>e.preventDefault();return a}
function renderFiles(){const q=state.q.toLowerCase();const r=files.filter(f=>(state.cat==='Toutes'||f.cat===state.cat)&&(!q||[f.title,f.desc,f.cat,f.provider].join(' ').toLowerCase().includes(q)));$('grid').replaceChildren(...r.map(card));$('count').textContent=`${r.length} fichier${r.length!==1?'s':''}`;$('empty').classList.toggle('hidden',r.length>0)}
$('search').oninput=e=>{state.q=e.target.value.slice(0,100);renderFiles()};$('go').onclick=renderFiles;$('reset').onclick=()=>{state.q='';state.cat='Toutes';$('search').value='';renderCats();renderFiles()};$('menu').onclick=()=>$('nav').classList.toggle('open');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=> $('nav').classList.remove('open'));renderCats();renderFiles();